version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/Vancouver"
    versioning-strategy: "increase"
    open-pull-requests-limit: 5
    groups:
      security-updates:
        applies-to: "security-updates"
        patterns:
          - "*"
      routine-updates:
        applies-to: "version-updates"
        patterns:
          - "*"
        update-types:
          - "minor"
          - "patch"
